In [4]:
import numpy as np

In [5]:
import pandas as pd

In [6]:
staff_df = pd.DataFrame([{'Name': 'Kelly', 'Role': 'Director of HR'},
                         {'Name': 'Sally', 'Role': 'Course liasion'},
                         {'Name': 'James', 'Role': 'Grader'}])
staff_df = staff_df.set_index('Name')
student_df = pd.DataFrame([{'Name': 'James', 'School': 'Business'},
                           {'Name': 'Mike', 'School': 'Law'},
                           {'Name': 'Sally', 'School': 'Engineering'}])

In [8]:
df = pd.read_csv('data/census.csv')

In [9]:
df

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

In [10]:
df[df['SUMLEV'] == 50]

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,1.072643,16.243199,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,-1.589565,0.972695,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-17.755986,-4.916350,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-11.637475,-0.827815,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,-11.752361,-8.040059,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294

In [13]:
(df.where(df['SUMLEV'] == 50)).dropna().set_index(['STNAME', 'CTYNAME'])

                           SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STNAME  CTYNAME
Alabama Autauga County       50.0     3.0       6.0    1.0     1.0
        Baldwin County       50.0     3.0       6.0    1.0     3.0
        Barbour County       50.0     3.0       6.0    1.0     5.0
        Bibb County          50.0     3.0       6.0    1.0     7.0
        Blount County        50.0     3.0       6.0    1.0     9.0
...                           ...     ...       ...    ...     ...
Wyoming Sweetwater County    50.0     4.0       8.0   56.0    37.0
        Teton County         50.0     4.0       8.0   56.0    39.0
        Uinta County         50.0     4.0       8.0   56.0    41.0
        Washakie County      50.0     4.0       8.0   56.0    43.0
        Weston County        50.0     4.0       8.0   56.0    45.0

                           CENSUS2010POP  ESTIMATESBASE2010  POPESTIMATE2010  \
STNAME  CTYNAME
Alabama Autauga County           54571.0            54571.0          54660.0
        Baldwin County          182265.0           182265.0         183193.0
        Barbour County           27457.0            27457.0          27341.0
        Bibb County              22915.0            22919.0          22861.0
        Blount County            57322.0            57322.0          57373.0
...                                  ...                ...              ...
Wyoming Sweetwater County        43806.0            43806.0          43593.0
        Teton County             21294.0            21294.0          21297.0
        Uinta County             21118.0            21118.0          21102.0
        Washakie County           8533.0             8533.0           8545.0
        Weston County             7208.0             7208.0           7181.0

                           POPESTIMATE2011  POPESTIMATE2012  ...  \
STNAME  CTYNAME                                              ...
Alabama Autauga County             55253.0          55175.0  ...
        Baldwin County            186659.0         190396.0  ...
        Barbour County             27226.0          27159.0  ...
        Bibb County                22733.0          22642.0  ...
        Blount County              57711.0          57776.0  ...
...                                    ...              ...  ...
Wyoming Sweetwater County          44041.0          45104.0  ...
        Teton County               21482.0          21697.0  ...
        Uinta County               20912.0          20989.0  ...
        Washakie County             8469.0           8443.0  ...
        Weston County               7114.0           7065.0  ...

                           RDOMESTICMIG2011  RDOMESTICMIG2012  \
STNAME  CTYNAME
Alabama Autauga County             7.242091         -2.915927
        Baldwin County            14.832960         17.647293
        Barbour County            -4.728132         -2.500690
        Bibb County               -5.527043         -5.068871
        Blount County              1.807375         -1.177622
...                                     ...               ...
Wyoming Sweetwater County          1.072643         16.243199
        Teton County              -1.589565          0.972695
        Uinta County             -17.755986         -4.916350
        Washakie County          -11.637475         -0.827815
        Weston County            -11.752361         -8.040059

                           RDOMESTICMIG2013  RDOMESTICMIG2014  \
STNAME  CTYNAME
Alabama Autauga County            -3.012349          2.265971
        Baldwin County            21.845705         19.243287
        Barbour County            -7.056824         -3.904217
        Bibb County               -6.201001         -0.177537
        Blount County             -1.748766         -2.062535
...                                     ...               ...
Wyoming Sweetwater County         -5.339774        -14.252889
        Teton County              19.525929         14.143021
        Uinta County              -6.902954        -14.215862
        Washakie County           -2.013502        -17.781491
        Weston County             12.372583          1.533635

                           RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  \
STNAME  CTYNAME
Alabama Autauga County            -2.530799     7.606016    -2.626146
        Baldwin County            17.197872    15.844176    18.559627
        Barbour County           -10.543299    -4.874741    -2.758113
        Bibb County                0.177258    -5.088389    -4.363636
        Blount County             -1.369970     1.859511    -0.848580
...                                     ...          ...          ...
Wyoming Sweetwater County        -14.248864     1.255221    16.243199
        Teton County              -0.564849     0.654527     2.408578
        Uinta County             -12.127022   -18.136812    -5.536861
        Washakie County            1.682288   -11.990126    -1.182592
        Weston County              6.935294   -12.032179    -8.040059

                           RNETMIG2013  RNETMIG2014  RNETMIG2015
STNAME  CTYNAME
Alabama Autauga County       -2.722002     2.592270    -2.187333
        Baldwin County       22.727626    20.317142    18.293499
        Barbour County       -7.167664    -3.978583   -10.543299
        Bibb County          -5.403729     0.754533     1.107861
        Blount County        -1.402476    -1.577232    -0.884411
...                                ...          ...          ...
Wyoming Sweetwater County    -5.295460   -14.075283   -14.070195
        Teton County         21.160658    16.308671     1.520747
        Uinta County         -7.521840   -14.740608   -12.606351
        Washakie County      -2.250385   -18.020168     1.441961
        Weston County        12.372583     1.533635     6.935294

[3142 rows x 98 columns]

In [15]:
(df.where(df['SUMLEV'] == 50)).dropna().set_index(['STNAME', 'CTYNAME']).rename(columns={'ESTIMATESBASE2010':'Estimated base 2010'})

                           SUMLEV  REGION  DIVISION  STATE  COUNTY  \
STNAME  CTYNAME
Alabama Autauga County       50.0     3.0       6.0    1.0     1.0
        Baldwin County       50.0     3.0       6.0    1.0     3.0
        Barbour County       50.0     3.0       6.0    1.0     5.0
        Bibb County          50.0     3.0       6.0    1.0     7.0
        Blount County        50.0     3.0       6.0    1.0     9.0
...                           ...     ...       ...    ...     ...
Wyoming Sweetwater County    50.0     4.0       8.0   56.0    37.0
        Teton County         50.0     4.0       8.0   56.0    39.0
        Uinta County         50.0     4.0       8.0   56.0    41.0
        Washakie County      50.0     4.0       8.0   56.0    43.0
        Weston County        50.0     4.0       8.0   56.0    45.0

                           CENSUS2010POP  Estimated base 2010  \
STNAME  CTYNAME
Alabama Autauga County           54571.0              54571.0
        Baldwin County          182265.0             182265.0
        Barbour County           27457.0              27457.0
        Bibb County              22915.0              22919.0
        Blount County            57322.0              57322.0
...                                  ...                  ...
Wyoming Sweetwater County        43806.0              43806.0
        Teton County             21294.0              21294.0
        Uinta County             21118.0              21118.0
        Washakie County           8533.0               8533.0
        Weston County             7208.0               7208.0

                           POPESTIMATE2010  POPESTIMATE2011  POPESTIMATE2012  \
STNAME  CTYNAME
Alabama Autauga County             54660.0          55253.0          55175.0
        Baldwin County            183193.0         186659.0         190396.0
        Barbour County             27341.0          27226.0          27159.0
        Bibb County                22861.0          22733.0          22642.0
        Blount County              57373.0          57711.0          57776.0
...                                    ...              ...              ...
Wyoming Sweetwater County          43593.0          44041.0          45104.0
        Teton County               21297.0          21482.0          21697.0
        Uinta County               21102.0          20912.0          20989.0
        Washakie County             8545.0           8469.0           8443.0
        Weston County               7181.0           7114.0           7065.0

                           ...  RDOMESTICMIG2011  RDOMESTICMIG2012  \
STNAME  CTYNAME            ...
Alabama Autauga County     ...          7.242091         -2.915927
        Baldwin County     ...         14.832960         17.647293
        Barbour County     ...         -4.728132         -2.500690
        Bibb County        ...         -5.527043         -5.068871
        Blount County      ...          1.807375         -1.177622
...                        ...               ...               ...
Wyoming Sweetwater County  ...          1.072643         16.243199
        Teton County       ...         -1.589565          0.972695
        Uinta County       ...        -17.755986         -4.916350
        Washakie County    ...        -11.637475         -0.827815
        Weston County      ...        -11.752361         -8.040059

                           RDOMESTICMIG2013  RDOMESTICMIG2014  \
STNAME  CTYNAME
Alabama Autauga County            -3.012349          2.265971
        Baldwin County            21.845705         19.243287
        Barbour County            -7.056824         -3.904217
        Bibb County               -6.201001         -0.177537
        Blount County             -1.748766         -2.062535
...                                     ...               ...
Wyoming Sweetwater County         -5.339774        -14.252889
        Teton County              19.525929         14.143021
        Uinta County              -6.902954        -14.215862
        Washakie County           -2.013502        -17.781491
        Weston County             12.372583          1.533635

                           RDOMESTICMIG2015  RNETMIG2011  RNETMIG2012  \
STNAME  CTYNAME
Alabama Autauga County            -2.530799     7.606016    -2.626146
        Baldwin County            17.197872    15.844176    18.559627
        Barbour County           -10.543299    -4.874741    -2.758113
        Bibb County                0.177258    -5.088389    -4.363636
        Blount County             -1.369970     1.859511    -0.848580
...                                     ...          ...          ...
Wyoming Sweetwater County        -14.248864     1.255221    16.243199
        Teton County              -0.564849     0.654527     2.408578
        Uinta County             -12.127022   -18.136812    -5.536861
        Washakie County            1.682288   -11.990126    -1.182592
        Weston County              6.935294   -12.032179    -8.040059

                           RNETMIG2013  RNETMIG2014  RNETMIG2015
STNAME  CTYNAME
Alabama Autauga County       -2.722002     2.592270    -2.187333
        Baldwin County       22.727626    20.317142    18.293499
        Barbour County       -7.167664    -3.978583   -10.543299
        Bibb County          -5.403729     0.754533     1.107861
        Blount County        -1.402476    -1.577232    -0.884411
...                                ...          ...          ...
Wyoming Sweetwater County    -5.295460   -14.075283   -14.070195
        Teton County         21.160658    16.308671     1.520747
        Uinta County         -7.521840   -14.740608   -12.606351
        Washakie County      -2.250385   -18.020168     1.441961
        Weston County        12.372583     1.533635     6.935294

[3142 rows x 98 columns]

In [19]:
def find_min_max(row):
    data = row[['POPESTIMATE2010',
                  'POPESTIMATE2011',
                  'POPESTIMATE2012',
                  'POPESTIMATE2013',
                  'POPESTIMATE2014',
                  'POPESTIMATE2015']]
    return pd.Series({'min' : np.min(data), 'max': np.max(data)})

In [21]:
df.apply(find_min_max, axis = 1)

          min      max
0     4785161  4858979
1       54660    55347
2      183193   203709
3       26489    27341
4       22512    22861
...       ...      ...
3188    43593    45162
3189    21297    23125
3190    20822    21102
3191     8316     8545
3192     7065     7234

[3193 rows x 2 columns]

In [ ]:
def find_min_max(row):
    data = row[['POPESTIMATE2010',
                  'POPESTIMATE2011',
                  'POPESTIMATE2012',
                  'POPESTIMATE2013',
                  'POPESTIMATE2014',
                  'POPESTIMATE2015']]
    row['min'] = np.min(data)
    row['max'] = np.max(data)
    return row

In [ ]:
df.apply(find_min_max, axis = 1)

In [ ]:
rows = ['POPESTIMATE2010',
                  'POPESTIMATE2011',
                  'POPESTIMATE2012',
                  'POPESTIMATE2013',
                  'POPESTIMATE2014',
                  'POPESTIMATE2015']

In [ ]:
rows

In [ ]:
df.apply(lambda x: np.max(x[rows]), axis=1)

In [ ]:
df.apply(lambda x: pd.Series({'max' : np.max(x[rows]), 'min' : np.min(x[rows])}), axis=1)

In [ ]:
df = pd.read_csv('data/census.csv')

In [ ]:
df = df[df['SUMLEV'] == 50]

In [ ]:
df.head()

In [ ]:
df['STNAME'].unique()

In [ ]:
%%timeit -n 10
for state in df['STNAME'].unique():
    avg = np.average(df.where(df['STNAME'] == state).dropna()['CENSUS2010POP'])
    print('Average population in ' + state + ' is' + str(avg))

In [ ]:
df.groupby['STNAME']

In [ ]:
for group, frame in df.groupby('STNAME'):
    avg = np.average(frame['CENSUS2010POP'])
    print('Average population in ' + group + ' is' + str(avg))

In [26]:
df.apply(find_min_max, axis = 1)

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015,min,max
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594,4785161,4858979
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333,54660,55347
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499,183193,203709
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299,26489,27341
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861,22512,22861
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3188,50,4,8,56,37,Wyoming,Sweetwater County,43806,43806,43593,...,-5.339774,-14.252889,-14.248864,1.255221,16.243199,-5.295460,-14.075283,-14.070195,43593,45162
3189,50,4,8,56,39,Wyoming,Teton County,21294,21294,21297,...,19.525929,14.143021,-0.564849,0.654527,2.408578,21.160658,16.308671,1.520747,21297,23125
3190,50,4,8,56,41,Wyoming,Uinta County,21118,21118,21102,...,-6.902954,-14.215862,-12.127022,-18.136812,-5.536861,-7.521840,-14.740608,-12.606351,20822,21102
3191,50,4,8,56,43,Wyoming,Washakie County,8533,8533,8545,...,-2.013502,-17.781491,1.682288,-11.990126,-1.182592,-2.250385,-18.020168,1.441961,8316,8545
3192,50,4,8,56,45,Wyoming,Weston County,7208,7208,7181,...,12.372583,1.533635,6.935294,-12.032179,-8.040059,12.372583,1.533635,6.935294,7065,7234

In [28]:
rows = ['POPESTIMATE2010',
                  'POPESTIMATE2011',
                  'POPESTIMATE2012',
                  'POPESTIMATE2013',
                  'POPESTIMATE2014',
                  'POPESTIMATE2015']

In [29]:
rows

['POPESTIMATE2010',
 'POPESTIMATE2011',
 'POPESTIMATE2012',
 'POPESTIMATE2013',
 'POPESTIMATE2014',
 'POPESTIMATE2015']

In [31]:
df.apply(lambda x: np.max(x[rows]), axis=1)

0       4858979
1         55347
2        203709
3         27341
4         22861
         ...
3188      45162
3189      23125
3190      21102
3191       8545
3192       7234
Length: 3193, dtype: int64

In [36]:
df.apply(lambda x: pd.Series({'max' : np.max(x[rows]), 'min' : np.min(x[rows])}), axis=1)

          max      min
0     4858979  4785161
1       55347    54660
2      203709   183193
3       27341    26489
4       22861    22512
...       ...      ...
3188    45162    43593
3189    23125    21297
3190    21102    20822
3191     8545     8316
3192     7234     7065

[3193 rows x 2 columns]

In [52]:
df = pd.read_csv('data/census.csv')

In [39]:
df = df[df['SUMLEV'] == 50]

In [41]:
df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411

In [42]:
df['STNAME'].unique()

array(['Alabama', 'Alaska', 'Arizona', 'Arkansas', 'California',
       'Colorado', 'Connecticut', 'Delaware', 'District of Columbia',
       'Florida', 'Georgia', 'Hawaii', 'Idaho', 'Illinois', 'Indiana',
       'Iowa', 'Kansas', 'Kentucky', 'Louisiana', 'Maine', 'Maryland',
       'Massachusetts', 'Michigan', 'Minnesota', 'Mississippi',
       'Missouri', 'Montana', 'Nebraska', 'Nevada', 'New Hampshire',
       'New Jersey', 'New Mexico', 'New York', 'North Carolina',
       'North Dakota', 'Ohio', 'Oklahoma', 'Oregon', 'Pennsylvania',
       'Rhode Island', 'South Carolina', 'South Dakota', 'Tennessee',
       'Texas', 'Utah', 'Vermont', 'Virginia', 'Washington',
       'West Virginia', 'Wisconsin', 'Wyoming'], dtype=object)

In [ ]:
%%timeit -n 10
for state in df['STNAME'].unique():
    avg = np.average(df.where(df['STNAME'] == state).dropna()['CENSUS2010POP'])
    print('Average population in ' + state + ' is' + str(avg))

In [48]:
df.groupby('STNAME')

In [ ]:
for group, frame in df.groupby('STNAME'):
    avg = np.average(frame['CENSUS2010POP'])
    print('Average population in ' + group + ' is' + str(avg))

In [49]:
def func(item):
    if

SyntaxError: invalid syntax (<ipython-input-49-eea902b7567c>, line 2)

In [ ]:
df['CENSUS2010POP'].agg()

In [ ]:
### agg should have Dictionary or List only
df.groupby('STNAME')['CENSUS2010POP', 'ESTIMATESBASE2010'].agg([np.average, np.sum])

In [ ]:
df = pd.read_csv('data/cars.csv')

In [ ]:
df

In [ ]:
df.pivot_table?

In [ ]:
df.pivot_table(values='(kW)', index = 'YEAR', columns='Make', aggfunc=[np.mean, np.min])

In [ ]:
df.pivot_table(values='(kW)', index = 'YEAR', columns='Make', aggfunc=[np.mean, np.min]).T.set_index()

In [50]:
df.pivot_table(values='(kW)', index = 'YEAR', columns='Make', aggfunc=[np.mean, np.min]).T.set_index()

Empty DataFrame
Columns: []
Index: []

In [59]:
### agg should have Dictionary or List only
df.groupby('STNAME')['CENSUS2010POP', 'ESTIMATESBASE2010'].agg([np.average, np.sum])

<ipython-input-59-0cbd0136aadf>:2: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby('STNAME')['CENSUS2010POP', 'ESTIMATESBASE2010'].agg([np.average, np.sum])

                     CENSUS2010POP           ESTIMATESBASE2010
                           average       sum           average       sum
STNAME
Alabama               1.405805e+05   9559472      1.405920e+05   9560254
Alaska                4.734873e+04   1420462      4.734993e+04   1420498
Arizona               7.990021e+05  12784034      7.990384e+05  12784614
Arkansas              7.673468e+04   5831836      7.673574e+04   5831916
California            1.262846e+06  74507912      1.262865e+06  74509006
Colorado              1.547445e+05  10058392      1.547484e+05  10058648
Connecticut           7.942438e+05   7148194      7.942484e+05   7148236
Delaware              4.489670e+05   1795868      4.489680e+05   1795872
District of Columbia  6.017230e+05   1203446      6.017670e+05   1203534
Florida               5.529797e+05  37602620      5.530771e+05  37609246
Georgia               1.210957e+05  19375306      1.211085e+05  19377362
Hawaii                4.534337e+05   2720602      4.534337e+05   2720602
Idaho                 6.967031e+04   3135164      6.967342e+04   3135304
Illinois              2.491385e+05  25661264      2.491563e+05  25663098
Indiana               1.394366e+05  12967604      1.394458e+05  12968458
Iowa                  6.092710e+04   6092710      6.093738e+04   6093738
Kansas                5.383242e+04   5706236      5.383268e+04   5706264
Kentucky              7.172507e+04   8678734      7.172478e+04   8678698
Louisiana             1.394884e+05   9066744      1.394917e+05   9066958
Maine                 1.562778e+05   2656722      1.562778e+05   2656722
Maryland              4.618842e+05  11547104      4.619028e+05  11547570
Massachusetts         8.730172e+05  13095258      8.730423e+05  13095634
Michigan              2.353248e+05  19767280      2.353364e+05  19768258
Minnesota             1.205438e+05  10607850      1.205438e+05  10607850
Mississippi           7.150113e+04   5934594      7.152055e+04   5936206
Missouri              1.032574e+05  11977854      1.032574e+05  11977854
Montana               3.471632e+04   1978830      3.471639e+04   1978834
Nebraska              3.885832e+04   3652682      3.885832e+04   3652682
Nevada                3.000612e+05   5401102      3.000768e+05   5401382
New Hampshire         2.393582e+05   2632940      2.393575e+05   2632932
New Jersey            7.992631e+05  17583788      7.992669e+05  17583872
New Mexico            1.211282e+05   4118358      1.211289e+05   4118384
New York              6.151778e+05  38756204      6.151774e+05  38756174
North Carolina        1.888214e+05  19070966      1.888256e+05  19071384
North Dakota          2.491078e+04   1345182      2.491078e+04   1345182
Ohio                  2.592473e+05  23073008      2.592522e+05  23073450
Oklahoma              9.618849e+04   7502702      9.619528e+04   7503232
Oregon                2.070851e+05   7662148      2.070850e+05   7662146
Pennsylvania          3.735994e+05  25404758      3.736143e+05  25405774
Rhode Island          3.508557e+05   2105134      3.509770e+05   2105862
South Carolina        1.968240e+05   9250728      1.968256e+05   9250802
South Dakota          2.430388e+04   1628360      2.430421e+04   1628382
Tennessee             1.322105e+05  12692210      1.322141e+05  12692550
Texas                 1.972201e+05  50291122      1.972244e+05  50292210
Utah                  1.842590e+05   5527770      1.842592e+05   5527776
Vermont               8.343213e+04   1251482      8.343267e+04   1251490
Virginia              1.193718e+05  15995826      1.194186e+05  16002090
Washington            3.362270e+05  13449080      3.362272e+05  13449086
West Virginia         6.617836e+04   3705988      6.617896e+04   3706022
Wisconsin             1.558078e+05  11373972      1.558161e+05  11374578
Wyoming               4.696883e+04   1127252      4.698058e+04   1127534

In [63]:
df = pd.read_csv('data/cars.csv')

In [64]:
df

,YEAR,Make,Model,Size,(kW),Unnamed: 5,TYPE,CITY (kWh/100 km),HWY (kWh/100 km),COMB (kWh/100 km),CITY (Le/100 km),HWY (Le/100 km),COMB (Le/100 km),(g/km),RATING,(km),TIME (h)
0,2012,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
1,2012,NISSAN,LEAF,MID-SIZE,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,0,NaN,117,7
2,2013,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,NaN,122,4
3,2013,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
4,2013,NISSAN,LEAF,MID-SIZE,80,A1,B,19.3,23.0,21.1,2.2,2.6,2.4,0,NaN,117,7
5,2013,SMART,FORTWO ELECTRIC DRIVE CABRIOLET,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
6,2013,SMART,FORTWO ELECTRIC DRIVE COUPE,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
7,2013,TESLA,MODEL S (40 kWh battery),FULL-SIZE,270,A1,B,22.4,21.9,22.2,2.5,2.5,2.5,0,NaN,224,6
8,2013,TESLA,MODEL S (60 kWh battery),FULL-SIZE,270,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,NaN,335,10
9,2013,TESLA,MODEL S (85 kWh battery),FULL-SIZE,270,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
10,2013,TESLA,MODEL S PERFORMANCE,FULL-SIZE,310,A1,B,23.9,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
11,2014,CHEVROLET,SPARK EV,SUBCOMPACT,104,A1,B,16.0,19.6,17.8,1.8,2.2,2.0,0,NaN,131,7
12,2014,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,NaN,122,4
13,2014,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
14,2014,NISSAN,LEAF,MID-SIZE,80,A1,B,16.5,20.8,18.4,1.9,2.3,2.1,0,NaN,135,5
15,2014,SMART,FORTWO ELECTRIC DRIVE CABRIOLET,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
16,2014,SMART,FORTWO ELECTRIC DRIVE COUPE,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
17,2014,TESLA,MODEL S (60 kWh battery),FULL-SIZE,225,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,NaN,335,10
18,2014,TESLA,MODEL S (85 kWh battery),FULL-SIZE,270,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
19,2014,TESLA,MODEL S PERFORMANCE,FULL-SIZE,310,A1,B,23.9,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
20,2015,BMW,i3,SUBCOMPACT,125,A1,B,15.2,18.8,16.8,1.7,2.1,1.9,0,NaN,130,4
21,2015,CHEVROLET,SPARK EV,SUBCOMPACT,104,A1,B,16.0,19.6,17.8,1.8,2.2,2.0,0,NaN,131,7
22,2015,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,NaN,122,4
23,2015,KIA,SOUL EV,STATION WAGON - SMALL,81,A1,B,17.5,22.7,19.9,2.0,2.6,2.2,0,NaN,149,4
24,2015,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,NaN,100,7
25,2015,NISSAN,LEAF,MID-SIZE,80,A1,B,16.5,20.8,18.4,1.9,2.3,2.1,0,NaN,135,5
26,2015,SMART,FORTWO ELECTRIC DRIVE CABRIOLET,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
27,2015,SMART,FORTWO ELECTRIC DRIVE COUPE,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,NaN,109,8
28,2015,TESLA,MODEL S (60 kWh battery),FULL-SIZE,283,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,NaN,335,10
29,2015,TESLA,MODEL S (70 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,377,12
30,2015,TESLA,MODEL S (85/90 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,NaN,426,12
31,2015,TESLA,MODEL S 70D,FULL-SIZE,280,A1,B,20.8,20.6,20.7,2.3,2.3,2.3,0,NaN,386,12
32,2015,TESLA,MODEL S 85D/90D,FULL-SIZE,280,A1,B,22.0,19.8,21.0,2.5,2.2,2.4,0,NaN,435,12
33,2015,TESLA,MODEL S P85D/P90D,FULL-SIZE,515,A1,B,23.4,21.5,22.5,2.6,2.4,2.5,0,NaN,407,12
34,2016,BMW,i3,SUBCOMPACT,125,A1,B,15.2,18.8,16.8,1.7,2.1,1.9,0,10.0,130,4
35,2016,CHEVROLET,SPARK EV,SUBCOMPACT,104,A1,B,16.0,19.6,17.8,1.8,2.2,2.0,0,10.0,131,7
36,2016,FORD,FOCUS ELECTRIC,COMPACT,107,A1,B,19.0,21.1,20.0,2.1,2.4,2.2,0,10.0,122,4
37,2016,KIA,SOUL EV,STATION WAGON - SMALL,81,A1,B,17.5,22.7,19.9,2.0,2.6,2.2,0,10.0,149,4
38,2016,MITSUBISHI,i-MiEV,SUBCOMPACT,49,A1,B,16.9,21.4,18.7,1.9,2.4,2.1,0,10.0,100,7
39,2016,NISSAN,LEAF (24 kWh battery),MID-SIZE,80,A1,B,16.5,20.8,18.4,1.9,2.3,2.1,0,10.0,135,5
40,2016,NISSAN,LEAF (30 kWh battery),MID-SIZE,80,A1,B,17.0,20.7,18.6,1.9,2.3,2.1,0,10.0,172,6
41,2016,SMART,FORTWO ELECTRIC DRIVE CABRIOLET,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,10.0,109,8
42,2016,SMART,FORTWO ELECTRIC DRIVE COUPE,TWO-SEATER,35,A1,B,17.2,22.5,19.6,1.9,2.5,2.2,0,10.0,109,8
43,2016,TESLA,MODEL S (60 kWh battery),FULL-SIZE,283,A1,B,22.2,21.7,21.9,2.5,2.4,2.5,0,10.0,335,10
44,2016,TESLA,MODEL S (70 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,10.0,377,12
45,2016,TESLA,MODEL S (85/90 kWh battery),FULL-SIZE,283,A1,B,23.8,23.2,23.6,2.7,2.6,2.6,0,10.0,426,12
46,2016,TESLA,MODEL S 70D,FULL-SIZE,386,A1,B,20.8,20.6,20.7,2.3,2.3,2.3,0,10.0,386,12
47,2016,TESLA,MODEL S 85D/90D,FULL-SIZE,386,A1,B,22.0,19.8,21.0,2.5,2.2,2.4,0,10.0,435,12
48,2016,TESLA,MODEL S 90D (Refresh),FULL-SIZE,386,A1,B,20.8,19.7,20.3,2.3,2.2,2.3,0,10.0,473,12
49,2016,TESLA,MODEL S P85D/P90D,FULL-SIZE,568,A1,B,23.4,21.5,22.5,2.6,2.4,2.5,0,10.0,407,12
50,2016,TESLA,MODEL S P90D (Refresh),FULL-SIZE,568,A1,B,22.9,21.0,22.1,2.6,2.4,2.5,0,10.0,435,12
51,2016,TESLA,MODEL X 90D,SUV - STANDARD,386,A1,B,23.2,22.2,22.7,2.6,2.5,2.6,0,10.0,414,12
52,2016,TESLA,MODEL X P90D,SUV - STANDARD,568,A1,B,23.6,23.3,23.5,2.7,2.6,2.6,0,10.0,402,12

In [66]:
df.pivot_table?

In [71]:
df.pivot_table(values='(kW)', index = 'YEAR', columns='Make', aggfunc=[np.mean, np.min])

       mean                                                              amin  \
Make    BMW CHEVROLET   FORD   KIA MITSUBISHI NISSAN SMART       TESLA    BMW
YEAR
2012    NaN       NaN    NaN   NaN       49.0   80.0   NaN         NaN    NaN
2013    NaN       NaN  107.0   NaN       49.0   80.0  35.0  280.000000    NaN
2014    NaN     104.0  107.0   NaN       49.0   80.0  35.0  268.333333    NaN
2015  125.0     104.0  107.0  81.0       49.0   80.0  35.0  320.666667  125.0
2016  125.0     104.0  107.0  81.0       49.0   80.0  35.0  409.700000  125.0


Make CHEVROLET   FORD   KIA MITSUBISHI NISSAN SMART  TESLA
YEAR
2012       NaN    NaN   NaN       49.0   80.0   NaN    NaN
2013       NaN  107.0   NaN       49.0   80.0  35.0  270.0
2014     104.0  107.0   NaN       49.0   80.0  35.0  225.0
2015     104.0  107.0  81.0       49.0   80.0  35.0  280.0
2016     104.0  107.0  81.0       49.0   80.0  35.0  283.0

In [76]:
df.pivot_table(values='(kW)', index = 'YEAR', columns='Make', aggfunc=[np.mean, np.min]).T.set_index()

TypeError: set_index() missing 1 required positional argument: 'keys'